# Generated by Django 3.0.4 on 2020-10-06 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeup', models.CharField(max_length=600)),
                ('validations', models.IntegerField(default=1)),
                ('date_c', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PostModel', to='index.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_dat', models.CharField(max_length=100)),
                ('comment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='index.PostModel')),
            ],
        ),
    ]
