# Generated by Django 3.0.4 on 2020-10-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='validations',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to='index.UserModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='index.PostModel'),
        ),
        migrations.CreateModel(
            name='validations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='index.PostModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='index.UserModel')),
            ],
        ),
    ]
