# Generated by Django 3.0.4 on 2020-10-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201006_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
    ]
