# Generated by Django 3.0.4 on 2020-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_postmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
