# Generated by Django 3.0.4 on 2020-10-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_postmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='title',
        ),
    ]
