# Generated by Django 3.0.4 on 2020-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201011_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.CharField(default='write your bio', max_length=200),
        ),
    ]
